global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api
    static_configs:
      - targets: ["api:8080"]

  - job_name: gateway
    static_configs:
      - targets: ["gateway:80"]

  - job_name: logging
    static_configs:
      - targets: ["logging:8082"]