gateway:
  mode: standalone  # standalone/auth
  port: 80
  consul_address: consul:8500

services:
  # Các service mặc định
  api:
    name: api-service
    urls: ["http://api:8080"]
    prefixes: ["/api/v1"]
    auth_required: false

  logging:
    name: logging-service
    urls: ["http://logging-service:8082"]
    prefixes: ["/api/logs"]
    auth_required: false

  # Service template cho các microservice khác
  user:
    name: user-service
    urls: ["http://user-service:8081"]
    prefixes: ["/api/users"]
    auth_required: true

  notification:
    name: notification-service
    urls: ["http://notification-service:8083"]
    prefixes: ["/api/notifications"]
    auth_required: true

# Cấu hình cho chế độ auth
auth:
  enabled: false
  jwt_secret: your-secret-key
  jwt_expiration: 24
  api_key_enabled: false
  api_key_header: X-API-Key
  api_key_secret: change-this-in-production
  excluded_paths:
    - "/api/v1/auth/login"
    - "/api/v1/auth/register"
    - "/health"
    - "/metrics"
  
  # Cấu hình permission
  permissions:
    cache_ttl: 300
    refresh_interval: 60
    default_tenant: default

# Cấu hình cho service discovery
service_discovery:
  enabled: true
  provider: consul
  refresh_interval: 30

# Cấu hình cho rate limiting
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 50

# Cấu hình cho circuit breaker
circuit_breaker:
  enabled: true
  timeout: 30
  max_requests: 3
  interval: 10
  error_threshold: 0.6

# Cấu hình cho monitoring
monitoring:
  metrics_path: /metrics
  health_path: /health 