version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - API_MODE=${API_MODE:-standalone}
      - API_PORT=${API_PORT:-8080}
      - DB_ENABLED=${DB_ENABLED:-false}
      - CACHE_ENABLED=${CACHE_ENABLED:-false}
      - DISCOVERY_ENABLED=${DISCOVERY_ENABLED:-false}
      - METRICS_ENABLED=${METRICS_ENABLED:-false}
      - LOGGING_SERVICE_ENABLED=${LOGGING_SERVICE_ENABLED:-false}
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: ${API_REPLICAS:-1}
      resources:
        limits:
          cpus: '${API_CPU_LIMIT:-0.5}'
          memory: ${API_MEMORY_LIMIT:-512M}

networks:
  api_network:
    driver: bridge 