version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:${ES_VERSION:-7.9.3}
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms${ES_JVM_MIN:-512m} -Xmx${ES_JVM_MAX:-512m}"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ports:
      - "${ES_PORT:-9200}:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green\\|status.*yellow'"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: kibana:${KIBANA_VERSION:-7.9.3}
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    networks:
      - elk_network
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  elk_network:
    driver: bridge

volumes:
  elasticsearch_data: 